# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gimenez/Documents/ca/ray_files

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gimenez/Documents/ca/ray_files

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gimenez/Documents/ca/ray_files/CMakeFiles /home/gimenez/Documents/ca/ray_files//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gimenez/Documents/ca/ray_files/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ray_tracing_one_week

# Build rule for target.
ray_tracing_one_week: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ray_tracing_one_week
.PHONY : ray_tracing_one_week

# fast build rule for target.
ray_tracing_one_week/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/build
.PHONY : ray_tracing_one_week/fast

hittables/rt_aa_rect.o: hittables/rt_aa_rect.c.o

.PHONY : hittables/rt_aa_rect.o

# target to build an object file
hittables/rt_aa_rect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_aa_rect.c.o
.PHONY : hittables/rt_aa_rect.c.o

hittables/rt_aa_rect.i: hittables/rt_aa_rect.c.i

.PHONY : hittables/rt_aa_rect.i

# target to preprocess a source file
hittables/rt_aa_rect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_aa_rect.c.i
.PHONY : hittables/rt_aa_rect.c.i

hittables/rt_aa_rect.s: hittables/rt_aa_rect.c.s

.PHONY : hittables/rt_aa_rect.s

# target to generate assembly for a file
hittables/rt_aa_rect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_aa_rect.c.s
.PHONY : hittables/rt_aa_rect.c.s

hittables/rt_box.o: hittables/rt_box.c.o

.PHONY : hittables/rt_box.o

# target to build an object file
hittables/rt_box.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_box.c.o
.PHONY : hittables/rt_box.c.o

hittables/rt_box.i: hittables/rt_box.c.i

.PHONY : hittables/rt_box.i

# target to preprocess a source file
hittables/rt_box.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_box.c.i
.PHONY : hittables/rt_box.c.i

hittables/rt_box.s: hittables/rt_box.c.s

.PHONY : hittables/rt_box.s

# target to generate assembly for a file
hittables/rt_box.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_box.c.s
.PHONY : hittables/rt_box.c.s

hittables/rt_bvh.o: hittables/rt_bvh.c.o

.PHONY : hittables/rt_bvh.o

# target to build an object file
hittables/rt_bvh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_bvh.c.o
.PHONY : hittables/rt_bvh.c.o

hittables/rt_bvh.i: hittables/rt_bvh.c.i

.PHONY : hittables/rt_bvh.i

# target to preprocess a source file
hittables/rt_bvh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_bvh.c.i
.PHONY : hittables/rt_bvh.c.i

hittables/rt_bvh.s: hittables/rt_bvh.c.s

.PHONY : hittables/rt_bvh.s

# target to generate assembly for a file
hittables/rt_bvh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_bvh.c.s
.PHONY : hittables/rt_bvh.c.s

hittables/rt_const_medium.o: hittables/rt_const_medium.c.o

.PHONY : hittables/rt_const_medium.o

# target to build an object file
hittables/rt_const_medium.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_const_medium.c.o
.PHONY : hittables/rt_const_medium.c.o

hittables/rt_const_medium.i: hittables/rt_const_medium.c.i

.PHONY : hittables/rt_const_medium.i

# target to preprocess a source file
hittables/rt_const_medium.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_const_medium.c.i
.PHONY : hittables/rt_const_medium.c.i

hittables/rt_const_medium.s: hittables/rt_const_medium.c.s

.PHONY : hittables/rt_const_medium.s

# target to generate assembly for a file
hittables/rt_const_medium.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_const_medium.c.s
.PHONY : hittables/rt_const_medium.c.s

hittables/rt_hittable.o: hittables/rt_hittable.c.o

.PHONY : hittables/rt_hittable.o

# target to build an object file
hittables/rt_hittable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_hittable.c.o
.PHONY : hittables/rt_hittable.c.o

hittables/rt_hittable.i: hittables/rt_hittable.c.i

.PHONY : hittables/rt_hittable.i

# target to preprocess a source file
hittables/rt_hittable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_hittable.c.i
.PHONY : hittables/rt_hittable.c.i

hittables/rt_hittable.s: hittables/rt_hittable.c.s

.PHONY : hittables/rt_hittable.s

# target to generate assembly for a file
hittables/rt_hittable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_hittable.c.s
.PHONY : hittables/rt_hittable.c.s

hittables/rt_hittable_list.o: hittables/rt_hittable_list.c.o

.PHONY : hittables/rt_hittable_list.o

# target to build an object file
hittables/rt_hittable_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_hittable_list.c.o
.PHONY : hittables/rt_hittable_list.c.o

hittables/rt_hittable_list.i: hittables/rt_hittable_list.c.i

.PHONY : hittables/rt_hittable_list.i

# target to preprocess a source file
hittables/rt_hittable_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_hittable_list.c.i
.PHONY : hittables/rt_hittable_list.c.i

hittables/rt_hittable_list.s: hittables/rt_hittable_list.c.s

.PHONY : hittables/rt_hittable_list.s

# target to generate assembly for a file
hittables/rt_hittable_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_hittable_list.c.s
.PHONY : hittables/rt_hittable_list.c.s

hittables/rt_instance.o: hittables/rt_instance.c.o

.PHONY : hittables/rt_instance.o

# target to build an object file
hittables/rt_instance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_instance.c.o
.PHONY : hittables/rt_instance.c.o

hittables/rt_instance.i: hittables/rt_instance.c.i

.PHONY : hittables/rt_instance.i

# target to preprocess a source file
hittables/rt_instance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_instance.c.i
.PHONY : hittables/rt_instance.c.i

hittables/rt_instance.s: hittables/rt_instance.c.s

.PHONY : hittables/rt_instance.s

# target to generate assembly for a file
hittables/rt_instance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_instance.c.s
.PHONY : hittables/rt_instance.c.s

hittables/rt_moving_sphere.o: hittables/rt_moving_sphere.c.o

.PHONY : hittables/rt_moving_sphere.o

# target to build an object file
hittables/rt_moving_sphere.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_moving_sphere.c.o
.PHONY : hittables/rt_moving_sphere.c.o

hittables/rt_moving_sphere.i: hittables/rt_moving_sphere.c.i

.PHONY : hittables/rt_moving_sphere.i

# target to preprocess a source file
hittables/rt_moving_sphere.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_moving_sphere.c.i
.PHONY : hittables/rt_moving_sphere.c.i

hittables/rt_moving_sphere.s: hittables/rt_moving_sphere.c.s

.PHONY : hittables/rt_moving_sphere.s

# target to generate assembly for a file
hittables/rt_moving_sphere.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_moving_sphere.c.s
.PHONY : hittables/rt_moving_sphere.c.s

hittables/rt_sphere.o: hittables/rt_sphere.c.o

.PHONY : hittables/rt_sphere.o

# target to build an object file
hittables/rt_sphere.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_sphere.c.o
.PHONY : hittables/rt_sphere.c.o

hittables/rt_sphere.i: hittables/rt_sphere.c.i

.PHONY : hittables/rt_sphere.i

# target to preprocess a source file
hittables/rt_sphere.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_sphere.c.i
.PHONY : hittables/rt_sphere.c.i

hittables/rt_sphere.s: hittables/rt_sphere.c.s

.PHONY : hittables/rt_sphere.s

# target to generate assembly for a file
hittables/rt_sphere.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/hittables/rt_sphere.c.s
.PHONY : hittables/rt_sphere.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/main.c.s
.PHONY : main.c.s

materials/rt_material.o: materials/rt_material.c.o

.PHONY : materials/rt_material.o

# target to build an object file
materials/rt_material.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material.c.o
.PHONY : materials/rt_material.c.o

materials/rt_material.i: materials/rt_material.c.i

.PHONY : materials/rt_material.i

# target to preprocess a source file
materials/rt_material.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material.c.i
.PHONY : materials/rt_material.c.i

materials/rt_material.s: materials/rt_material.c.s

.PHONY : materials/rt_material.s

# target to generate assembly for a file
materials/rt_material.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material.c.s
.PHONY : materials/rt_material.c.s

materials/rt_material_dielectric.o: materials/rt_material_dielectric.c.o

.PHONY : materials/rt_material_dielectric.o

# target to build an object file
materials/rt_material_dielectric.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_dielectric.c.o
.PHONY : materials/rt_material_dielectric.c.o

materials/rt_material_dielectric.i: materials/rt_material_dielectric.c.i

.PHONY : materials/rt_material_dielectric.i

# target to preprocess a source file
materials/rt_material_dielectric.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_dielectric.c.i
.PHONY : materials/rt_material_dielectric.c.i

materials/rt_material_dielectric.s: materials/rt_material_dielectric.c.s

.PHONY : materials/rt_material_dielectric.s

# target to generate assembly for a file
materials/rt_material_dielectric.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_dielectric.c.s
.PHONY : materials/rt_material_dielectric.c.s

materials/rt_material_diffuse.o: materials/rt_material_diffuse.c.o

.PHONY : materials/rt_material_diffuse.o

# target to build an object file
materials/rt_material_diffuse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_diffuse.c.o
.PHONY : materials/rt_material_diffuse.c.o

materials/rt_material_diffuse.i: materials/rt_material_diffuse.c.i

.PHONY : materials/rt_material_diffuse.i

# target to preprocess a source file
materials/rt_material_diffuse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_diffuse.c.i
.PHONY : materials/rt_material_diffuse.c.i

materials/rt_material_diffuse.s: materials/rt_material_diffuse.c.s

.PHONY : materials/rt_material_diffuse.s

# target to generate assembly for a file
materials/rt_material_diffuse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_diffuse.c.s
.PHONY : materials/rt_material_diffuse.c.s

materials/rt_material_diffuse_light.o: materials/rt_material_diffuse_light.c.o

.PHONY : materials/rt_material_diffuse_light.o

# target to build an object file
materials/rt_material_diffuse_light.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_diffuse_light.c.o
.PHONY : materials/rt_material_diffuse_light.c.o

materials/rt_material_diffuse_light.i: materials/rt_material_diffuse_light.c.i

.PHONY : materials/rt_material_diffuse_light.i

# target to preprocess a source file
materials/rt_material_diffuse_light.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_diffuse_light.c.i
.PHONY : materials/rt_material_diffuse_light.c.i

materials/rt_material_diffuse_light.s: materials/rt_material_diffuse_light.c.s

.PHONY : materials/rt_material_diffuse_light.s

# target to generate assembly for a file
materials/rt_material_diffuse_light.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_diffuse_light.c.s
.PHONY : materials/rt_material_diffuse_light.c.s

materials/rt_material_isotropic.o: materials/rt_material_isotropic.c.o

.PHONY : materials/rt_material_isotropic.o

# target to build an object file
materials/rt_material_isotropic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_isotropic.c.o
.PHONY : materials/rt_material_isotropic.c.o

materials/rt_material_isotropic.i: materials/rt_material_isotropic.c.i

.PHONY : materials/rt_material_isotropic.i

# target to preprocess a source file
materials/rt_material_isotropic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_isotropic.c.i
.PHONY : materials/rt_material_isotropic.c.i

materials/rt_material_isotropic.s: materials/rt_material_isotropic.c.s

.PHONY : materials/rt_material_isotropic.s

# target to generate assembly for a file
materials/rt_material_isotropic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_isotropic.c.s
.PHONY : materials/rt_material_isotropic.c.s

materials/rt_material_metal.o: materials/rt_material_metal.c.o

.PHONY : materials/rt_material_metal.o

# target to build an object file
materials/rt_material_metal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_metal.c.o
.PHONY : materials/rt_material_metal.c.o

materials/rt_material_metal.i: materials/rt_material_metal.c.i

.PHONY : materials/rt_material_metal.i

# target to preprocess a source file
materials/rt_material_metal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_metal.c.i
.PHONY : materials/rt_material_metal.c.i

materials/rt_material_metal.s: materials/rt_material_metal.c.s

.PHONY : materials/rt_material_metal.s

# target to generate assembly for a file
materials/rt_material_metal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/materials/rt_material_metal.c.s
.PHONY : materials/rt_material_metal.c.s

rt_aabb.o: rt_aabb.c.o

.PHONY : rt_aabb.o

# target to build an object file
rt_aabb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_aabb.c.o
.PHONY : rt_aabb.c.o

rt_aabb.i: rt_aabb.c.i

.PHONY : rt_aabb.i

# target to preprocess a source file
rt_aabb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_aabb.c.i
.PHONY : rt_aabb.c.i

rt_aabb.s: rt_aabb.c.s

.PHONY : rt_aabb.s

# target to generate assembly for a file
rt_aabb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_aabb.c.s
.PHONY : rt_aabb.c.s

rt_camera.o: rt_camera.c.o

.PHONY : rt_camera.o

# target to build an object file
rt_camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_camera.c.o
.PHONY : rt_camera.c.o

rt_camera.i: rt_camera.c.i

.PHONY : rt_camera.i

# target to preprocess a source file
rt_camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_camera.c.i
.PHONY : rt_camera.c.i

rt_camera.s: rt_camera.c.s

.PHONY : rt_camera.s

# target to generate assembly for a file
rt_camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_camera.c.s
.PHONY : rt_camera.c.s

rt_colour.o: rt_colour.c.o

.PHONY : rt_colour.o

# target to build an object file
rt_colour.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_colour.c.o
.PHONY : rt_colour.c.o

rt_colour.i: rt_colour.c.i

.PHONY : rt_colour.i

# target to preprocess a source file
rt_colour.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_colour.c.i
.PHONY : rt_colour.c.i

rt_colour.s: rt_colour.c.s

.PHONY : rt_colour.s

# target to generate assembly for a file
rt_colour.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_colour.c.s
.PHONY : rt_colour.c.s

rt_hit.o: rt_hit.c.o

.PHONY : rt_hit.o

# target to build an object file
rt_hit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_hit.c.o
.PHONY : rt_hit.c.o

rt_hit.i: rt_hit.c.i

.PHONY : rt_hit.i

# target to preprocess a source file
rt_hit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_hit.c.i
.PHONY : rt_hit.c.i

rt_hit.s: rt_hit.c.s

.PHONY : rt_hit.s

# target to generate assembly for a file
rt_hit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_hit.c.s
.PHONY : rt_hit.c.s

rt_perlin.o: rt_perlin.c.o

.PHONY : rt_perlin.o

# target to build an object file
rt_perlin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_perlin.c.o
.PHONY : rt_perlin.c.o

rt_perlin.i: rt_perlin.c.i

.PHONY : rt_perlin.i

# target to preprocess a source file
rt_perlin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_perlin.c.i
.PHONY : rt_perlin.c.i

rt_perlin.s: rt_perlin.c.s

.PHONY : rt_perlin.s

# target to generate assembly for a file
rt_perlin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_perlin.c.s
.PHONY : rt_perlin.c.s

rt_skybox_simple.o: rt_skybox_simple.c.o

.PHONY : rt_skybox_simple.o

# target to build an object file
rt_skybox_simple.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_skybox_simple.c.o
.PHONY : rt_skybox_simple.c.o

rt_skybox_simple.i: rt_skybox_simple.c.i

.PHONY : rt_skybox_simple.i

# target to preprocess a source file
rt_skybox_simple.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_skybox_simple.c.i
.PHONY : rt_skybox_simple.c.i

rt_skybox_simple.s: rt_skybox_simple.c.s

.PHONY : rt_skybox_simple.s

# target to generate assembly for a file
rt_skybox_simple.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/rt_skybox_simple.c.s
.PHONY : rt_skybox_simple.c.s

scenes/rt_scenes.o: scenes/rt_scenes.c.o

.PHONY : scenes/rt_scenes.o

# target to build an object file
scenes/rt_scenes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/scenes/rt_scenes.c.o
.PHONY : scenes/rt_scenes.c.o

scenes/rt_scenes.i: scenes/rt_scenes.c.i

.PHONY : scenes/rt_scenes.i

# target to preprocess a source file
scenes/rt_scenes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/scenes/rt_scenes.c.i
.PHONY : scenes/rt_scenes.c.i

scenes/rt_scenes.s: scenes/rt_scenes.c.s

.PHONY : scenes/rt_scenes.s

# target to generate assembly for a file
scenes/rt_scenes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/scenes/rt_scenes.c.s
.PHONY : scenes/rt_scenes.c.s

textures/rt_texture.o: textures/rt_texture.c.o

.PHONY : textures/rt_texture.o

# target to build an object file
textures/rt_texture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture.c.o
.PHONY : textures/rt_texture.c.o

textures/rt_texture.i: textures/rt_texture.c.i

.PHONY : textures/rt_texture.i

# target to preprocess a source file
textures/rt_texture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture.c.i
.PHONY : textures/rt_texture.c.i

textures/rt_texture.s: textures/rt_texture.c.s

.PHONY : textures/rt_texture.s

# target to generate assembly for a file
textures/rt_texture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture.c.s
.PHONY : textures/rt_texture.c.s

textures/rt_texture_checker_pattern.o: textures/rt_texture_checker_pattern.c.o

.PHONY : textures/rt_texture_checker_pattern.o

# target to build an object file
textures/rt_texture_checker_pattern.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_checker_pattern.c.o
.PHONY : textures/rt_texture_checker_pattern.c.o

textures/rt_texture_checker_pattern.i: textures/rt_texture_checker_pattern.c.i

.PHONY : textures/rt_texture_checker_pattern.i

# target to preprocess a source file
textures/rt_texture_checker_pattern.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_checker_pattern.c.i
.PHONY : textures/rt_texture_checker_pattern.c.i

textures/rt_texture_checker_pattern.s: textures/rt_texture_checker_pattern.c.s

.PHONY : textures/rt_texture_checker_pattern.s

# target to generate assembly for a file
textures/rt_texture_checker_pattern.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_checker_pattern.c.s
.PHONY : textures/rt_texture_checker_pattern.c.s

textures/rt_texture_image.o: textures/rt_texture_image.c.o

.PHONY : textures/rt_texture_image.o

# target to build an object file
textures/rt_texture_image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_image.c.o
.PHONY : textures/rt_texture_image.c.o

textures/rt_texture_image.i: textures/rt_texture_image.c.i

.PHONY : textures/rt_texture_image.i

# target to preprocess a source file
textures/rt_texture_image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_image.c.i
.PHONY : textures/rt_texture_image.c.i

textures/rt_texture_image.s: textures/rt_texture_image.c.s

.PHONY : textures/rt_texture_image.s

# target to generate assembly for a file
textures/rt_texture_image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_image.c.s
.PHONY : textures/rt_texture_image.c.s

textures/rt_texture_noise.o: textures/rt_texture_noise.c.o

.PHONY : textures/rt_texture_noise.o

# target to build an object file
textures/rt_texture_noise.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_noise.c.o
.PHONY : textures/rt_texture_noise.c.o

textures/rt_texture_noise.i: textures/rt_texture_noise.c.i

.PHONY : textures/rt_texture_noise.i

# target to preprocess a source file
textures/rt_texture_noise.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_noise.c.i
.PHONY : textures/rt_texture_noise.c.i

textures/rt_texture_noise.s: textures/rt_texture_noise.c.s

.PHONY : textures/rt_texture_noise.s

# target to generate assembly for a file
textures/rt_texture_noise.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_noise.c.s
.PHONY : textures/rt_texture_noise.c.s

textures/rt_texture_solid_colour.o: textures/rt_texture_solid_colour.c.o

.PHONY : textures/rt_texture_solid_colour.o

# target to build an object file
textures/rt_texture_solid_colour.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_solid_colour.c.o
.PHONY : textures/rt_texture_solid_colour.c.o

textures/rt_texture_solid_colour.i: textures/rt_texture_solid_colour.c.i

.PHONY : textures/rt_texture_solid_colour.i

# target to preprocess a source file
textures/rt_texture_solid_colour.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_solid_colour.c.i
.PHONY : textures/rt_texture_solid_colour.c.i

textures/rt_texture_solid_colour.s: textures/rt_texture_solid_colour.c.s

.PHONY : textures/rt_texture_solid_colour.s

# target to generate assembly for a file
textures/rt_texture_solid_colour.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ray_tracing_one_week.dir/build.make CMakeFiles/ray_tracing_one_week.dir/textures/rt_texture_solid_colour.c.s
.PHONY : textures/rt_texture_solid_colour.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ray_tracing_one_week"
	@echo "... hittables/rt_aa_rect.o"
	@echo "... hittables/rt_aa_rect.i"
	@echo "... hittables/rt_aa_rect.s"
	@echo "... hittables/rt_box.o"
	@echo "... hittables/rt_box.i"
	@echo "... hittables/rt_box.s"
	@echo "... hittables/rt_bvh.o"
	@echo "... hittables/rt_bvh.i"
	@echo "... hittables/rt_bvh.s"
	@echo "... hittables/rt_const_medium.o"
	@echo "... hittables/rt_const_medium.i"
	@echo "... hittables/rt_const_medium.s"
	@echo "... hittables/rt_hittable.o"
	@echo "... hittables/rt_hittable.i"
	@echo "... hittables/rt_hittable.s"
	@echo "... hittables/rt_hittable_list.o"
	@echo "... hittables/rt_hittable_list.i"
	@echo "... hittables/rt_hittable_list.s"
	@echo "... hittables/rt_instance.o"
	@echo "... hittables/rt_instance.i"
	@echo "... hittables/rt_instance.s"
	@echo "... hittables/rt_moving_sphere.o"
	@echo "... hittables/rt_moving_sphere.i"
	@echo "... hittables/rt_moving_sphere.s"
	@echo "... hittables/rt_sphere.o"
	@echo "... hittables/rt_sphere.i"
	@echo "... hittables/rt_sphere.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... materials/rt_material.o"
	@echo "... materials/rt_material.i"
	@echo "... materials/rt_material.s"
	@echo "... materials/rt_material_dielectric.o"
	@echo "... materials/rt_material_dielectric.i"
	@echo "... materials/rt_material_dielectric.s"
	@echo "... materials/rt_material_diffuse.o"
	@echo "... materials/rt_material_diffuse.i"
	@echo "... materials/rt_material_diffuse.s"
	@echo "... materials/rt_material_diffuse_light.o"
	@echo "... materials/rt_material_diffuse_light.i"
	@echo "... materials/rt_material_diffuse_light.s"
	@echo "... materials/rt_material_isotropic.o"
	@echo "... materials/rt_material_isotropic.i"
	@echo "... materials/rt_material_isotropic.s"
	@echo "... materials/rt_material_metal.o"
	@echo "... materials/rt_material_metal.i"
	@echo "... materials/rt_material_metal.s"
	@echo "... rt_aabb.o"
	@echo "... rt_aabb.i"
	@echo "... rt_aabb.s"
	@echo "... rt_camera.o"
	@echo "... rt_camera.i"
	@echo "... rt_camera.s"
	@echo "... rt_colour.o"
	@echo "... rt_colour.i"
	@echo "... rt_colour.s"
	@echo "... rt_hit.o"
	@echo "... rt_hit.i"
	@echo "... rt_hit.s"
	@echo "... rt_perlin.o"
	@echo "... rt_perlin.i"
	@echo "... rt_perlin.s"
	@echo "... rt_skybox_simple.o"
	@echo "... rt_skybox_simple.i"
	@echo "... rt_skybox_simple.s"
	@echo "... scenes/rt_scenes.o"
	@echo "... scenes/rt_scenes.i"
	@echo "... scenes/rt_scenes.s"
	@echo "... textures/rt_texture.o"
	@echo "... textures/rt_texture.i"
	@echo "... textures/rt_texture.s"
	@echo "... textures/rt_texture_checker_pattern.o"
	@echo "... textures/rt_texture_checker_pattern.i"
	@echo "... textures/rt_texture_checker_pattern.s"
	@echo "... textures/rt_texture_image.o"
	@echo "... textures/rt_texture_image.i"
	@echo "... textures/rt_texture_image.s"
	@echo "... textures/rt_texture_noise.o"
	@echo "... textures/rt_texture_noise.i"
	@echo "... textures/rt_texture_noise.s"
	@echo "... textures/rt_texture_solid_colour.o"
	@echo "... textures/rt_texture_solid_colour.i"
	@echo "... textures/rt_texture_solid_colour.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

